name: Build Lovable Site

on:
  push:
    branches:
      - main

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Vincular Codigo
        uses: actions/checkout@v4

      - name: Instalar Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar Dependencias
        run: npm ci || npm install

      - name: Executar Build do Projeto
        run: npm run build

      - name: Compactar pasta de Saida
        run: |
          cd dist
          zip -r ../site-pronto.zip .
          cd ..

      - name: Disponibilizar para Download
        uses: actions/upload-artifact@v4
        with:
          name: site-producao
          path: site-pronto.zip
          retention-days: 7
